export const GET_API_RESULT = "GET_API_RESULT";
export const GET_API_RESULT_FAIL = "GET_API_RESULT_FAIL";

export const GET_JAVA_RESULT = "GET_JAVA_RESULT";
export const GET_JAVA_RESULT_FAIL = "GET_JAVA_RESULT_FAIL";


